// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindowsExplorer.Models;

#nullable disable

namespace WindowsExplorer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230805121857_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindowsExplorer.Models.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FolderInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("IdFolder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderInfoId");

                    b.ToTable("FileInfo");
                });

            modelBuilder.Entity("WindowsExplorer.Models.FolderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FolderInfo");
                });

            modelBuilder.Entity("WindowsExplorer.Models.FileInfo", b =>
                {
                    b.HasOne("WindowsExplorer.Models.FolderInfo", "FolderInfo")
                        .WithMany()
                        .HasForeignKey("FolderInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
